name: test

on:
  workflow_dispatch:

  push:

    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write
  packages: write

env:
  MY_ENV_VAR: initial value

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: step-1
        shell: bash
        run: |
          printf 'Hello %s\n' "$MY_ENV_VAR"
          echo "{MY_ENV_VAR}='new value'" >> $GITHUB_ENV
          printf 'Hello %s\n' "$MY_ENV_VAR"

      - name: step-2
        shell: bash
        run: |
          printf 'Hello %s\n' "$MY_ENV_VAR"
